<?php

// This file is automatically generated by Laravel...

return [
    App\Providers\ApiServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
];
